import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Zap, Code2, Layers } from "lucide-react";
import JSZip from "jszip";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import ImageUpload from "@/components/ImageUpload";
import CodePreview from "@/components/CodePreview";
import { supabase } from "@/integrations/supabase/client";

interface GeneratedResult {
  analysis: {
    sections: string[];
    colorPalette: string[];
    fonts: string[];
    summary: string;
  };
  html: string;
  css: string;
}

const Index = () => {
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [result, setResult] = useState<GeneratedResult | null>(null);
  const { toast } = useToast();

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const dataUrl = reader.result as string;
        const base64 = dataUrl.split(",")[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const handleGenerate = async () => {
    if (!selectedImage) return;

    setIsProcessing(true);
    setResult(null);

    try {
      const imageBase64 = await fileToBase64(selectedImage);

      const { data, error } = await supabase.functions.invoke("analyze-design", {
        body: { imageBase64, mimeType: selectedImage.type },
      });

      if (error) throw error;
      if (data?.error) throw new Error(data.error);

      setResult(data as GeneratedResult);
      toast({
        title: "Code generated!",
        description: "Your website code is ready to download.",
      });
    } catch (err: any) {
      console.error("Generation error:", err);
      toast({
        title: "Generation failed",
        description: err.message || "Something went wrong. Try again.",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const handleDownload = async () => {
    if (!result) return;
    const zip = new JSZip();
    zip.file("index.html", result.html);
    zip.file("style.css", result.css);
    zip.file(
      "README.md",
      `# Generated Website\n\n${result.analysis.summary}\n\n## Sections\n${result.analysis.sections.map((s) => `- ${s}`).join("\n")}\n\n## Colors\n${result.analysis.colorPalette.join(", ")}\n\nGenerated by Design → Code AI`
    );
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "generated-website.zip";
    a.click();
    URL.revokeObjectURL(url);
  };

  const features = [
    { icon: Layers, label: "Layout Detection", desc: "Identifies sections, grids & hierarchy" },
    { icon: Sparkles, label: "AI Analysis", desc: "Gemini Pro vision model" },
    { icon: Code2, label: "Clean Code", desc: "Semantic HTML + Bootstrap 5" },
    { icon: Zap, label: "Instant Export", desc: "Download-ready ZIP package" },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Header */}
      <header className="relative overflow-hidden border-b border-border">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-accent/5" />
        <div className="relative max-w-5xl mx-auto px-6 py-16 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium mb-6">
              <Sparkles className="w-4 h-4" />
              AI-Powered Design to Code
            </div>
            <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-foreground mb-4">
              Design → Code
              <span className="text-primary"> in Seconds</span>
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Upload any UI screenshot or Figma export. Get production-ready
              HTML, CSS & Bootstrap code instantly.
            </p>
          </motion.div>

          {/* Feature pills */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="flex flex-wrap justify-center gap-4 mt-10"
          >
            {features.map((f) => (
              <div
                key={f.label}
                className="flex items-center gap-2.5 px-4 py-2.5 rounded-xl bg-card border border-border"
              >
                <f.icon className="w-4 h-4 text-primary" />
                <div className="text-left">
                  <p className="text-sm font-medium text-foreground">{f.label}</p>
                  <p className="text-xs text-muted-foreground">{f.desc}</p>
                </div>
              </div>
            ))}
          </motion.div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-5xl mx-auto px-6 py-12 space-y-8">
        {/* Upload Section */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <ImageUpload
            onImageSelect={setSelectedImage}
            selectedImage={selectedImage}
            onClear={() => {
              setSelectedImage(null);
              setResult(null);
            }}
            isProcessing={isProcessing}
          />

          <AnimatePresence>
            {selectedImage && !result && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="flex justify-center mt-6"
              >
                <Button
                  onClick={handleGenerate}
                  disabled={isProcessing}
                  size="lg"
                  className="gap-2 px-8 text-base font-semibold"
                >
                  {isProcessing ? (
                    <>
                      <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                      Analyzing Design...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-5 h-5" />
                      Generate Code
                    </>
                  )}
                </Button>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.section>

        {/* Results */}
        <AnimatePresence>
          {result && (
            <CodePreview
              html={result.html}
              css={result.css}
              analysis={result.analysis}
              onDownload={handleDownload}
            />
          )}
        </AnimatePresence>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-8 text-center text-sm text-muted-foreground">
        <p>Powered by Gemini Pro Vision • Bootstrap 5 • Semantic HTML5</p>
      </footer>
    </div>
  );
};

export default Index;
